lm-sensors/lm-sensors

etc/sensors.conf.default
This adds Fintek F71868A inputs that are hardwired inside the chip (in0,
in7, in8, in9) to sensors.conf.default with appropriate scaling values.
=> Add hardwired Fintek F71868A inputs to sensors.conf.default

CHANGES, README, configs/Gigabyte/GA-M720-US3.conf, configs/MSI/MS-7302-K9A2GM-V.conf, configs/MSI/MS-7786-A55M-P33.conf, etc/sensors.conf.default, etc/sensors.conf.eg
Most mainboards need a config file which describe which input of a
monitoring chip is connected to which voltage rail, what are scaling
factors of voltages that can't be measured directly by the chip, which
part of the board has each temperature sensor, which fan is connected to
which tachometer input of the chip, etc.
All these data need to be determined either from a board schematic (if
available) or by a trial-and-error method.
This can be a time consuming and error-prone work, fortunately, it needs to
be done just once per mainboard.
Currently, however, there is no standard mechanism to share such
configurations so multiple users of the same board don't basically waste
their time reinventing the wheel (or recreating the same configuration
again and again).
Previously, a wiki on an old …
=> Add 'configs' directory where sample configurations can be stored

configs/Axiomtek/CAPA800.conf
This PR adds board configuration file for Axiomtek CAPA800 Intel Atom
single board computer, which uses Winbond W83627UHG as its Super I/O.
Input routing and scaling on this board is mostly based on SIO datasheet
recommended setup, small differences were determined experimentally by
comparing sensors output with a BIOS screen.
Signed-off-by: Maciej S. Szmigiero <mail@maciej.szmigiero.name>
=> Add Axiomtek CAPA800 board config file

etc/sensors.conf.default
It looks like Nuvoton NCT6795D has the same hardwired inputs as other
members of its family, so let's add it to the appropriate section of
sensors.conf.default.
This was determined experimentally on a MSI MS-7A34 (B350 TOMAHAWK) board.
=> Add hardwired Nuvoton NCT6795D inputs

configs/ASRock/AB350_Pro4.conf, configs/Asus/P8B75-V.conf, configs/HP/MicroServer_N40L.conf
New configs for the following:
1. ASRock AB350 Pro4 Motherboard
2. HP MicroServer N40L System
3. Asus P8B75-V Motherboard
=> ASRock AB350 Pro4, HP MicroServer N40L and Asus P8B75-V configs

prog/detect/sensors-detect
Kernel support was added in commit
https://github.com/torvalds/linux/commit/877d8948d0aa402fb
=> Add detection of AMD Ryzen w/ Vega graphics

lib/libsensors.3
Minor addition to the documentation to show the bus member of sensors_chip_name.  This becomes important when calling sensors_get_adapter_name(), which requires knowledge of this relationship.
Thanks!
-Elliott
=> Adding documentation of the chip_name to bus_id relationship.

configs/Gigabyte/GA-AX370-DS3H.conf, configs/Gigabyte/GA-AX370M-DS3H.conf
This board is very similar to the GA-AB350-GAMING3 board.
The config was only tested on a board with an it8686 chip.
=> configs: Add Gigabyte GA-AX370M-DS3H Motherboard

etc/sensors.conf.default
It seems Nuvoton NCT6796D also has the same hardwired inputs.
This was determined experimentally on an ASUS PRIME B360M-A board.
Signed-off-by: Roy Zhang <pudh4418@gmail.com>
=> sensors.conf.default: Add hardwired NCT6796D inputs

configs/Gigabyte/GA-F2A88XM-HD3.conf, configs/MSI/MS-7A34-B350-TOMAHAWK.conf
This pull request adds configs for Gigabyte GA-F2A88XM-HD3 and MSI MS-7A34 (B350 TOMAHAWK)
boards.
Input routings and scalings were read from schematic of either the board itself
(in the GA-F2A88XM-HD3 case) or from a similar board (in the MSI MS-7A34 case),
then confirmed experimentally.
=> add Gigabyte GA-F2A88XM-HD3 and MSI MS-7A34 (B350 TOMAHAWK) config

prog/sensord/args.c, prog/sensord/args.h, prog/sensord/sense.c, prog/sensord/sensord.8
Add an option `-1`/`--oneline` that logs the updates sensor value with the chip and adapter on the same line.
This makes it easier to parse and uniquely identify sensors without labels, such as `temp1` in the example below.
Without `--oneline`:
```
Chip: iwlwifi-virtual-0
Adapter: Virtual device
temp1: 35.0 C
Chip: coretemp-isa-0000
Adapter: ISA adapter
Package id 0: 46.0 C
Core 0: 43.0 C
Core 1: 43.0 C
Core 2: 39.0 C
Core 3: 41.0 C
Chip: acpitz-virtual-0
Adapter: Virtual device
temp1: 25.0 C
Chip: dell_smm-virtual-0
Adapter: Virtual device
Processor Fan: 2512 RPM
Video Fan: 2498 RPM
CPU: 46.0 C
Ambient: 54.0 C
Ambient: 47.0 C
Other: 40.0 C
Chip: pch_skylake-virtual-0
Adapter: Virtual device
temp1: 66.0 C
```
With `--oneline`:
```
Chip: iwlwifi-virtual-0 Adapter: Virtual device  temp1: …
```
=> sensord: add oneline sensor log output option

configs/SuperMicro/X7DCL.conf
Add configuration for Supermicro X7DCL motherboard.
Based on slightly modified setup of X7DBE from this repo.
Runtime tested on X7DCL-3 rev. 1.1a
So far there is only support for onboard sensors,
no support for PSU failure yet, nor external PMBus sensors.
Signed-off-by: Lech Perczak <lech.perczak@gmail.com>
=> configs: add Supermicro X7DCL

doc/fancontrol.txt, prog/pwm/fancontrol, prog/pwm/fancontrol.8
This option defines how many last temperature readings are used to average the temperature.
It can be used to smoothen short temperature peaks.
If this value isn't defined, it defaults to 1 (no averaging).
Multidimensional arrays are not supported in bash, so the result is not very pretty, but it's working and I commented all these quirks so it's easier to understand.
=> Adding AVERAGE option to fancontrol

prog/detect/sensors-detect
Support for the Fintek F75387SG/RG was added to driver f75375s back in 2013 according to https://hwmon.wiki.kernel.org/device_support_status_d_f. Works perfectly on my computer.
=> Add driver for Fintek F75387SG/RG to sensors-detect

configs/SuperMicro/X7DCL.conf
According to:
"Quad-Core Intel® Xeon(R) Processor 5400 Series Electrical Specifications"
(table 2-12), FSB termination voltage of the CPUs (VTT) is 1.1V +/-5%.
Initial configuration set it to 1.2V - fix that.
Signed-off-by: Lech Perczak <lech.perczak@gmail.com>
=> configs: fix Supermicro X7DCL VTT limits

prog/detect/sensors-detect
NCT6797D is found on MPG X570 GAMING PLUS
For NCT6798D I don't have any HW using it but it's supported by the nct6775 driver
=> Add new Nuvoton Super IO Sensors

prog/sensors/chips.c
scale_value is generic function for scaling values. There is a lower
resolution then json format provides for voltage and current.
The patch is calling scale_value() and showing values with higher
resolution.
For example on Xilinx ZynqMP platform:
ina226-i2c-3-41
Adapter: i2c-0-mux (chan_id 0)
in0:           2.00 mV
in1:         848.00 mV
power1:      287.50 mW
curr1:       330.00 mA
Signed-off-by: Michal Simek <monstr@monstr.eu>
=> sensors: Scale voltage and current values

Makefile
`uname -m` lists the host machine architecture. To support cross-compilation
the Makefile should detect the compiler's target architecture. This approach
uses the `gcc`/`clang` compatible `-dumpmachine` option and parses the first
word in the tuple representing the target architecture.
Renaming `MACHINE` to `ARCH` to match cross-compiler conventions for
specifying the target architecture (e.g.
`make ARCH=arm CC=arm-linux-gnueabi-gcc`)
Just like for PPC the `isadump` and `isaset` tools should not be compiled
on ARM. This has the side affect of "fixing" the ARM build with glibc-2.30,
which removed `sys/io.h` I/O port functions.
Fixes #190
Signed-off-by: Lucas Magasweran <lucas.magasweran@ieee.org>
=> makefile: use compiler target arch when determining what programs to compile

prog/sensors/chips.c
Hey there !
Back in 2017 when the `-j` option has been added (1b36ea429930b05e1b3cb77cdbc24cb1ffbcac61), the Fahrenheit conversion has not been implemented.
This quick-and-dirty patch fixes this behavior, making both `-j` and `-f` options _compatible_.
It has been tested on my own Debian system.
Bye :wave:
EDIT : New commit added afterwards relative to the `-u` (raw output) flag.
=> Fixes Fahrenheit missing conversion for JSON and RAW output modes

configs/Gigabyte/X470-AORUS-ULTRA-GAMING.conf
Initial config for Gigabyte X470 AORUS ULTRA GAMING
https://www.gigabyte.com/Motherboard/X470-AORUS-ULTRA-GAMING-rev-10
This config is based on:
- GA-AB350-GAMING3.conf
- GA-AX370-GAMING5.conf
- output of HWiNFO64 Sensor Status program on Windows
=> configs: add support for X470 ultra gaming (WIP)

configs/Asus/P10S-M_WS.conf
Add configs for Asus motherboard **P10S-M WS**, which is very similar to **H87-Pro**.
=> Add configs for ASUS MB P10S-M WS

prog/detect/sensors-detect
This patch adds support for the FTS Teutates Chip, used on Fujitsu Mainboards for Intel Skylake and later Chipsets. It is based on a patch from Fujitsu and was tested on a D-3446-S Mainboard.
The corresponding kernel module can be found [here](https://github.com/torvalds/linux/blob/master/drivers/hwmon/ftsteutates.c#L711).
This is a revised version of this [pull request](https://github.com/lm-sensors/lm-sensors/pull/9).
=> sensors-detect: add support for FSC Teutates Chip

prog/init/fancontrol.service, prog/init/sensord.service
/var/run is considered a legacy directory by systemd 239+ and having it in unit files causes a warning to be emitted to the journal.
Example warning:
```
/usr/lib/systemd/system/sensord.service:8: PIDFile= references a path below legacy directory /var/run/, updating /var/run/sensord.pid → /run/sensord.pid; please update the unit file accordingly.
```
systemd change reference:
https://github.com/systemd/systemd/commit/a2d1fb882c4308bc10362d971f333c5031d60069
=> Change PIDFile path from /var/run to /run in systemd service units

configs/Gigabyte/GA-AB350N-GAMING-WIFI-REV1.0.conf
I've not written configs for lm-sensors before so input is welcome. I used the manual and images provided by the manufacture to write this config along with a large amount of screenshots from HWiNFO64 from Windows.
=> configs: Add entry for GA-AB350N-Gaming WIFI (rev. 1.0)

configs/Gigabyte/GA-AB350N-GAMING-WIFI-REV1.0.conf
Hopefully this commit message is a bit better than my other attempt, sorry for all the trouble.
=> configs: Add DMI information for GA-AB350N-Gaming WIFI (rev. 1.0)

configs/ASRock/Z390M-ITX-ac.conf
This is a configuration for an ASRock Z390M ITX/ac motherboard. Sensor data is cross referenced from ASRock's A-Tuning application data, as well as physical testing of the board. Some fan rpm parameters are still up to the user to adjust as necessary for their specific implementation.
=> Config for ASRock Z390M ITX

prog/detect/sensors-detect
Enable sensors-detect support for AMD Zen3 (Family 19h) CPUs. This PCI ID
is derived from Linux kernel PCI_DEVICE_ID_AMD_19H_DF_F3.
Signed-off-by: Wei Huang <wei.huang2@amd.com>
=> sensors-detect: Add support for AMD CPU Family 19h

prog/detect/sensors-detect
This is a companion to https://marc.info/?l=lm-sensors&m=160681657707434&w=2.
Tested on an MSI MAG B550M MORTAR motherboard.
=> sensors-detect: Add support for NCT6687D.

configs/Biostar/A960D+V2.conf
As the subject says, sensors output seems to match the BIOS display.
=> Add Biostar A960D+V2 config

prog/pwm/fancontrol
I was experimenting with `fancontrol` directly (rather than running it as a `systemd` service). I got an error message saying that the configuration file is missing, even though it did exist. It turns out that I forgot to run `fancontrol` as the `root` user, and so the config file was not _writeable_.
This PR makes the corresponding error message more accurate. Additionally, it improves a couple of other error messages.
=> Improve some error messages of fancontrol

configs/Lenovo/ThinkPad-X260-i5.conf
This PR adds a configuration for a Lenovo ThinkPad X260 with an Intel i5 processor. It may also work fine for other flavors of the X260 laptops but I cannot test this.
=> Add sensors config file for Lenovo ThinkPad X260
